#!/bin/bash
#a bash script to create a template perl script
#20151004 Kuan Huang

usage="new_python <new python script> #number of inputs#"

#author of perl script
name=`finger $USER | grep Name | cut -f 3 -d':' | sed s'/ //'`

if [ $# -gt 0 ]; then
#"shebang" for perl
	echo "#!/bin/python" > $1
#file creation & authorship
	echo -n "#" >> $1
	timestamp=$(date "+%d %B %Y")
	echo -n "$timestamp" >> $1
	echo " - $name - " >> $1
	echo "" >> $1
# file description
	#echo "\"\"\"" 
	#echo "\"\"\""
#package use
	echo "import sys" >> $1
	echo "import argparse" >> $1
	# echo "import Bio" >> $1" # biopython if needed
	echo "" >> $1
#perl script usage
	echo "INPUT = \"input\"" >> $1
	echo "" >> $1
	echo "def usage():" >> $1
	echo "	helpText = \"USAGE: $1 [-h] --\" + INPUT + \" <input file>\\n\"" >> $1
	echo "	helpText += \"\\t-h	this message\\n\"" >> $1
	echo "	helpText += \"\\t--\" + INPUT + \"	input file\\n\"" >> $1
	echo "	return helpText" >> $1
	echo "" >> $1
# get arguments
	echo "def getArguments():" >> $1
	echo "	filename = None" >> $1
	echo "	parser = argparse.ArgumentParser( description = usage() )" >> $1
	echo "	parser.add_argument( \"--\" + INPUT , \"-i\" )" >> $1
	echo "	return vars( parser.parse_args() )" >> $1
	echo "" >> $1
	echo "def readFile( inFile ):" >> $1
	echo "	#open input file" >> $1
	echo "	try:" >> $1
	echo "		with open( inFile , \"r\" ) as f:" >> $1
	echo "			for line in f:" >> $1
	echo "				line = line.strip()" >> $1
	echo "				fields = line.split( \"\\t\" )" >> $1
	echo "	except:" >> $1
	echo "		print( \"ERROR: Bad input file\\n\" )" >> $1
	echo "		print( usage() )" >> $1
	echo "		sys.exit()" >> $1
	echo "" >> $1
	echo "def main():" >> $1
	echo "	data = getArguments()" >> $1
	echo "	readFile( data[INPUT] )" >> $1
	echo "" >> $1
	echo "sys.exit( main() )" >> $1
fi
exit
